version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

python:
  install:
    - requirements: docs/sphinx/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/sphinx/conf.py
  fail_on_warning: true

conda:
  environment: environment.yml
