name: histogram-dev
channels:
  - mcvine
  - conda-forge
dependencies:
  - check-wheel-contents
  - coverage
  - numpy >= 1.20.3,< 2.0
  - python >=3.8
  - pyre == 0.8.3
  - journal==0.8.4
  - matplotlib
  - h5py
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - sphinx
  - sphinx-rtd-theme
  - versioningit
  - setuptools
