name: histogram-dev
channels:
  - mcvine
  - conda-forge
dependencies:
  - anaconda-client
  - boa
  - libmamba
  - libarchive
  - conda-build
  - conda-verify
  - check-wheel-contents
  - coverage
  - cmake
  - gxx_linux-64
  - numpy == 1.26.4
  - python >=3.10
  - pyre == 0.8.3
  - matplotlib
  - h5py
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - sphinx
  - sphinx-rtd-theme
  - versioningit
  - setuptools
