name: histogram-conda_build_only
channels:
  - mcvine
  - conda-forge
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - coverage
  - numpy
  - scipy
  - python >=3.8
  - pyre == 0.8.3
  - libmamba
  - libarchive
  - journal==0.8.4
  - pre-commit
  - pytest
  - pytest-cov
  - python-build
  - sphinx
  - sphinx-rtd-theme
  - versioningit
  - setuptools
