# load information from pyproject.toml
#{% set pyproject = load_file_data("pyproject.toml", from_recipe_dir=True) %}
#{% set project = {{ PIXI_PACKAGE_NAME }} %}
#{% set license = project.get('license').get('text') %}
#{% set description = project.get('description') %}
#{% set project_url = pyproject.get('project', {}).get('urls') %}
#{% set url = project_url.get('homepage') %}
# this will get the version set by environment variable
#{% set tool_conf = pyproject.get('tool', {}) %}
#{% set version = tool_conf.get('pixi',{}).get('package',{}).get('version',{}) %}
#{% set version_number = version.split('+')[0] %}
# change the build number by hand if you want to rebuild the package
context:
  build_number: 0

package:
  name: histogram
  version: 0.0.0

source:
  path: ..


build:
  script:
    # env:
    #   - ${{ compiler("c") }}
    #   - ${{ compiler("cxx") }}
  noarch: python
  number: ${{ build_number }}

requirements:
  host:
    - python
    - versioningit
    - setuptools>=42
    - wheel

  build:
    - setuptools>=42
    - versioningit

  run:
    - numpy
    - matplotlib
    - h5py

# test:
#   imports:
#     - histogram

about:
  #home: {{ url }}
  #summary: {{ description }}
  #license: BSD
  license_file: null
