#-*- Makefile -*-
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                               Michael A.G. Aivazis
#                        California Institute of Technology
#                        (C) 1998-2004  All Rights Reserved
#
# <LicenseText>
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#

PROJECT = histogram
PACKAGE = DeveloperGuide

# directory structure

BUILD_DIRS = \

OTHER_DIRS = \


RECURSE_DIRS = $(BUILD_DIRS) $(OTHER_DIRS)

#--------------------------------------------------------------------------
#

all: 
	BLD_ACTION="all" $(MM) recurse

distclean::
	BLD_ACTION="distclean" $(MM) recurse

clean::
	BLD_ACTION="clean" $(MM) recurse

tidy:: tidy-tmpxml tidy-tmpxsl
	BLD_ACTION="tidy" $(MM) recurse

export::
	BLD_ACTION="export" $(MM) recurse

test::
	BLD_ACTION="test" $(MM) recurse



#docbook source file extension
EXT_XML = xml
#docbook source could contain things that are pointing to 
#moving target. For example, a html link that might move.
#So I do not really create docbook xml by hand, but rather 
#generate docbook xml file from a txml file. This might not
#be a very good idea. It works for now.
EXT_TXML = txml


#Where is the doxgen documentation?
DOXYGEN_DOCS = http://arcscluster.caltech.edu:5001/docs/histogram/histogram/html


#website target
WEBSITE = http://arcscluster.caltech.edu:5001



#modify the following line to specify the binary of
#xsltproc. maybe this should go into .tools
XSLTPROC = xsltproc



#docbook style sheet file for creating html chunks.
#the style sheet contains a reference to a local copy of
#"official" style sheet. Please modify the style sheet whenever 
#necessary.
CUSTOM_DB2HTML_XSL = mydocbook.xsl


#docbook style sheet file for creating latex file
#the style sheet contains a reference to local copy of
#official db2latex style sheet. Please modify the style sheet whenever 
#necessary.
CUSTOM_DB2LATEX_XSL = mydb2latex.xsl



#system style sheets
#May 1, 2007: following two env vars moved to .tools
#DB2HTML_XSL_DIR = $(HOME)/install/docbook/xsl/docbook-xsl-1.72.0/html
#DB2LATEX_XSL_DIR = $(HOME)/install/db2latex-xsl-0.8pre1/xsl




# --- no more configurable items ---

#custom style sheets contain references to system style sheets
#those references are created using make rules
$(CUSTOM_DB2HTML_XSL): $(CUSTOM_DB2HTML_XSL).t
	cat $< | sed 's|xxxDB2HTML_XSL_DIRxxx|$(DB2HTML_XSL_DIR)|g' > $@ 

$(CUSTOM_DB2LATEX_XSL): $(CUSTOM_DB2LATEX_XSL).t
	cat $< | sed 's|xxxDB2LATEX_XSL_DIRxxx|$(DB2LATEX_XSL_DIR)|g' > $@ 


tidy-tmpxsl:
	for i in $(CUSTOM_DB2LATEX_XSL)  $(CUSTOM_DB2HTML_XSL); do rm -f $$i; done



#this is the name of the main xml file of the docbook document
DOCBOOKMAIN = main


DOCBOOKSOURCEFILES = \
	Introduction.xml \
	NdArray.xml \


%.$(EXT_XML): %.$(EXT_TXML)
	cat $< | sed 's|xxxDoxygenDocsxxx|$(DOXYGEN_DOCS)|g' | sed 's|xxxWEBSITExxx|$(WEBSITE)|g'  >   $@ 


tidy-tmpxml::
	for i in $(DOCBOOKSOURCEFILES) ; do rm -f $$i; done


DOCBOOKMAINFILE = $(DOCBOOKMAIN).$(EXT_XML)

$(DOCBOOKMAINFILE): $(DOCBOOKSOURCEFILES)
	touch $(DOCBOOKMAINFILE)




include std-docs.def
EXPORT_HTML_DOC_DIR = $(EXPORT_DOCDIR)/html
EXPORT_LATEX_DOC_DIR = $(EXPORT_DOCDIR)/latex

$(EXPORT_HTML_DOC_DIR):
	$(MKDIR) $(MKPARENTS) $(EXPORT_HTML_DOC_DIR)

$(EXPORT_LATEX_DOC_DIR):
	$(MKDIR) $(MKPARENTS) $(EXPORT_LATEX_DOC_DIR)



HTML_INDEX = $(EXPORT_HTML_DOC_DIR)/index.html
HTML_TARBALL = $(EXPORT_DOCDIR)/$(PROJECT)-$(PACKAGE)-docs.tgz


EXPORT_HTML_FIGURES = $(EXPORT_HTML_DOC_DIR)/figures


$(EXPORT_HTML_FIGURES): figures uml
	cp -r figures $(EXPORT_HTML_DOC_DIR)
	for i in `ls uml/*.png uml/*.jpg uml/*.eps` ;\
	  do \
	    cp  $$i $(EXPORT_HTML_FIGURES) ;\
	  done


htmldoc: $(HTML_INDEX) 
$(HTML_INDEX): $(EXPORT_HTML_DOC_DIR) $(DOCBOOKMAINFILE) $(EXPORT_HTML_FIGURES) $(CUSTOM_DB2HTML_XSL)
	$(XSLTPROC) --nonet --stringparam base.dir $(EXPORT_HTML_DOC_DIR)/ $(CUSTOM_DB2HTML_XSL) $(DOCBOOKMAINFILE)


htmltarball: $(HTML_TARBALL)
$(HTML_TARBALL): $(HTML_INDEX)
	cd $(EXPORT_DOCDIR) && tar cvfz $(HTML_TARBALL) html && cd -


include std-latex.def
#override the std-latex because pdflatex is automatically called by the 
#latex document generated by db2latex
%.$(EXT_PDF): %.$(EXT_TEX)
	cd $(EXPORT_LATEX_DOC_DIR) && TEXINPUTS=.:: $(TEX_LATEX) $< && cd -
	cd $(EXPORT_LATEX_DOC_DIR) && TEXINPUTS=.:: $(TEX_LATEX) $< && cd -
	cd $(EXPORT_LATEX_DOC_DIR) && TEXINPUTS=.:: $(TEX_LATEX) $< && cd -
#	cd $(EXPORT_LATEX_DOC_DIR) && TEXINPUTS=.:$(PWD):: $(TEX_LATEX) $< && cd -



EXPORT_LATEX_FIGURES = $(EXPORT_LATEX_DOC_DIR)/figures
TEXFILE = $(EXPORT_LATEX_DOC_DIR)/$(DOCBOOKMAIN).$(EXT_TEX)
PDFFILE = $(EXPORT_LATEX_DOC_DIR)/$(DOCBOOKMAIN).$(EXT_PDF)
texdoc: $(TEXFILE) $(PDFFILE)
$(TEXFILE): $(EXPORT_LATEX_DOC_DIR) $(DOCBOOKMAINFILE) $(EXPORT_LATEX_FIGURES) $(CUSTOM_DB2LATEX_XSL)
	$(XSLTPROC) --nonet $(CUSTOM_DB2LATEX_XSL) $(DOCBOOKMAINFILE) > $(TEXFILE)


DB2LATEX_FIGURES = $(DB2LATEX_XSL_DIR)/figures

$(EXPORT_LATEX_FIGURES): figures uml $(DB2LATEX_FIGURES)
	$(MKDIR) $(MKPARENTS) $(EXPORT_LATEX_FIGURES)
	cp -r figures/* $(EXPORT_LATEX_FIGURES)
	cp -rf $(DB2LATEX_FIGURES)/* $(EXPORT_LATEX_FIGURES)
	for i in `ls uml/*.png uml/*.jpg`;\
	  do \
	    cp  $$i $(EXPORT_LATEX_FIGURES) ;\
	  done


#index.html in this directory is wrtten by hand.
#it serves as documentation index.
#It gives links to online
#html document, pdf document, and tar ball of html documents.
MAIN_HTML_INDEX = $(EXPORT_DOCDIR)/index.html
$(MAIN_HTML_INDEX): index.html
	cp index.html $(MAIN_HTML_INDEX)

mainindex: $(MAIN_HTML_INDEX)

docs:  htmldoc htmltarball texdoc mainindex


# version
# $Id: Make.mm 444 2006-03-31 07:20:49Z linjiao $

# End of file
