# load information from pyproject.toml
{% set pyproject = load_file_data('pyproject.toml')  %}
{% set project = pyproject.get('project', {}) %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
{% set project_url = pyproject.get('project', {}).get('urls') %}
{% set url = project_url.get('homepage') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
# change the build number by hand if you want to rebuild the package
{% set build_number = 0 %}

package:
  name: histogram
  version: {{ version_number }}

source:
  path: ../


build:
  script_env:
    - CC
    - CXX
  noarch: python
  number: {{ build_number }}
  #script: ./build.sh
  #string: py{{py}}
  #script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  #https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html

requirements:
  host:
    - python
    - versioningit
    - setuptools>=42
    - wheel

  build:
    - setuptools>=42
    - versioningit
    - python
    - cmake
    - pip

  run:
    - numpy

test:
  imports:
    - histogram

about:
  home: {{ url }}
  summary: {{ description }}
  license: BSD
  license_file: null
